
services:
  gtapp:
    # image: gt
    build:
      context: .
    container_name: giorgiotedesco
    environment:
      - NODE_ENV=dev
      - UID=1000
      - GID=1000
    user: "${UID}:${GID}"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /home/giorgionetg/WebSiteLogSeq:/app/logseq
      - /app/node_modules
    ports:
      - "3000:3000"
    command: yarn dev