/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
//import Cube from './cube.gltf';
import Cube from './cube.gltf';

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF(Cube)
  //const { nodes, materials } = props
  //console.log(props);
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.Material} geometry={nodes.Cube.geometry} />
    </group>
  )
}
