name: Deploy Preview

on:
  push:
    branches:
      - feature/preview

permissions:
  contents: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build (preview)
        run: PREVIEW=true yarn build

      - name: Deploy to /preview
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          destination_dir: preview
